// Copyright (c) 2026 WSO2 LLC (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// AgentCard signature verification (signature.bal), per specification
// section 8.4.
//
// The fixtures below (canonical payloads, protected headers, signatures)
// were generated with the REAL @a2a-js/sdk (npm, v1.0.1) - its actual
// generateAgentCardSignature/canonicalizeAgentCard - signing over keys
// generated by openssl and self-verified against openssl-issued X.509
// certificates before being embedded here (see the design plan for the
// full generation process). This is deliberate: a Ballerina-only
// self-consistency test (sign with our own code, verify with our own
// code) cannot catch a canonicalization mismatch, which is exactly the
// class of bug the previous, removed implementation had (it verified
// only its own serialization, never a real signer's). Only a genuinely
// external signature proves the JCS canonicalizer is right.
//
// tests/resources/jcs-fixture-ec-cert.pem and jcs-fixture-rsa-cert.pem
// hold the corresponding self-signed X.509 certificates, so the public
// keys here are decoded the same way any real caller would - there is no
// direct "decode a bare SPKI PEM" function in ballerina/crypto.

import ballerina/crypto;
import ballerina/test;

const string ES256_CANONICAL_PAYLOAD = "{\"capabilities\":{\"extendedAgentCard\":false,\"pushNotifications\":false,\"streaming\":true},\"defaultInputModes\":[\"text\"],\"defaultOutputModes\":[\"text\"],\"description\":\"Generated to verify ballerina/a2a against the real a2a-js signer (ES256)\",\"name\":\"JCS Fixture Agent ES256\",\"skills\":[{\"description\":\"Echoes the input back\",\"id\":\"echo\",\"name\":\"Echo\",\"tags\":[\"demo\",\"echo\"]}],\"supportedInterfaces\":[{\"protocolBinding\":\"JSONRPC\",\"protocolVersion\":\"1.0\",\"url\":\"https://fixture.example.com\"}],\"version\":\"1.0.0\"}";

const string RS256_CANONICAL_PAYLOAD = "{\"capabilities\":{\"extendedAgentCard\":false,\"pushNotifications\":true,\"streaming\":false},\"defaultInputModes\":[\"text\"],\"defaultOutputModes\":[\"text\"],\"description\":\"Generated to verify ballerina/a2a against the real a2a-js signer (RS256)\",\"name\":\"JCS Fixture Agent RS256\",\"skills\":[{\"description\":\"Echoes the input back\",\"id\":\"echo\",\"name\":\"Echo\"}],\"supportedInterfaces\":[{\"protocolBinding\":\"JSONRPC\",\"protocolVersion\":\"1.0\",\"url\":\"https://fixture.example.com\"}],\"version\":\"1.0.0\"}";

// The unsigned card, as fed to the real a2a-js canonicalizeAgentCard -
// deliberately includes default-shaped values (extensions: [],
// securitySchemes: {}, securityRequirements: [], skills[].examples: [])
// to exercise proto3 default-stripping in the same fixture.
isolated function es256FixtureCard() returns json => {
    name: "JCS Fixture Agent ES256",
    description: "Generated to verify ballerina/a2a against the real a2a-js signer (ES256)",
    version: "1.0.0",
    url: "https://fixture.example.com",
    capabilities: {streaming: true, pushNotifications: false, extendedAgentCard: false, extensions: []},
    defaultInputModes: ["text"],
    defaultOutputModes: ["text"],
    supportedInterfaces: [
        {url: "https://fixture.example.com", protocolBinding: "JSONRPC", protocolVersion: "1.0"}
    ],
    skills: [
        {id: "echo", name: "Echo", description: "Echoes the input back", tags: ["demo", "echo"], examples: []}
    ],
    securitySchemes: {},
    securityRequirements: []
};

isolated function es256FixtureSignedCard() returns json {
    map<json> signed = <map<json>>es256FixtureCard().clone();
    signed["signatures"] = [
        {
            protected: "eyJhbGciOiJFUzI1NiIsImtpZCI6ImZpeHR1cmUtZWMta2V5LTEiLCJ0eXAiOiJKT1NFIn0",
            signature: "UD_VWc3v4X9j9q5CqUS241N24pw47yCv-OJvqj3HVvL_N66wcDQ43pxafYfv7rHETqMBFGgymPBOhH-ToRP7xQ"
        }
    ];
    return signed;
}

isolated function rs256FixtureCard() returns json => {
    name: "JCS Fixture Agent RS256",
    description: "Generated to verify ballerina/a2a against the real a2a-js signer (RS256)",
    version: "1.0.0",
    url: "https://fixture.example.com",
    capabilities: {streaming: false, pushNotifications: true, extendedAgentCard: false},
    defaultInputModes: ["text"],
    defaultOutputModes: ["text"],
    supportedInterfaces: [
        {url: "https://fixture.example.com", protocolBinding: "JSONRPC", protocolVersion: "1.0"}
    ],
    skills: [{id: "echo", name: "Echo", description: "Echoes the input back", tags: []}],
    securitySchemes: {},
    securityRequirements: []
};

isolated function rs256FixtureSignedCard() returns json {
    map<json> signed = <map<json>>rs256FixtureCard().clone();
    signed["signatures"] = [
        {
            protected: "eyJhbGciOiJSUzI1NiIsImtpZCI6ImZpeHR1cmUtcnNhLWtleS0xIiwidHlwIjoiSk9TRSJ9",
            signature: "Q9sFTXaYyoPE1jPh7M9iHFKTQsbyNeebyHcoN-yVKNVWimwWNhsES6zFAagTZKO8OVAruUO1ZDNonDKIEYiQA9PBnbCm3Vem3JgaJMx9z3Nf0C_RvGn7-qiproURconQlPjR08HsetYSwAJZ3BMliUfvVBxGBDy3DTOCYkQ6xS3B4XKE9aiNGc4_hQ4sNXZzZrIS8xS7fNMC_P1eHxTYBhyu1kjsoePaYVq2-4Cfl_0VRTsuN7T2IHox1m2y7678cpsFbB3ak4V8Nv5Oey813ABK0IPungXmtvdKqf3k09JSw35H_IlA9d63x9eHo7gNcsthym4u2cZcJhIIZkOWYQ"
        }
    ];
    return signed;
}

// Relative to the package directory (a2a/) - this repo's CI
// (.github/workflows/ci.yml) runs `bal test` with `working-directory: a2a`,
// which is the authoritative convention, not whatever directory a given
// terminal invocation happens to sit in.
isolated function ecFixturePublicKey() returns crypto:PublicKey|error =>
    crypto:decodeEcPublicKeyFromCertFile("tests/resources/jcs-fixture-ec-cert.pem");

isolated function rsaFixturePublicKey() returns crypto:PublicKey|error =>
    crypto:decodeRsaPublicKeyFromCertFile("tests/resources/jcs-fixture-rsa-cert.pem");

// ---- canonicalization matches the real a2a-js output exactly ----------

@test:Config {}
function testCanonicalizeAgentCardBodyMatchesRealA2aJsOutputEs256() returns error? {
    string canonical = check canonicalizeAgentCardBody(es256FixtureCard());
    test:assertEquals(canonical, ES256_CANONICAL_PAYLOAD,
            "must byte-match the real @a2a-js/sdk canonicalizeAgentCard output, not just be internally consistent");
}

@test:Config {}
function testCanonicalizeAgentCardBodyMatchesRealA2aJsOutputRs256() returns error? {
    string canonical = check canonicalizeAgentCardBody(rs256FixtureCard());
    test:assertEquals(canonical, RS256_CANONICAL_PAYLOAD);
}

@test:Config {}
function testCanonicalizeAgentCardBodyExcludesSignaturesFieldRegardlessOfInput() returns error? {
    // Signing and verifying both canonicalize the same way per spec
    // 8.4.1 ("the signatures field MUST be excluded"); passing the
    // *signed* card (which carries signatures) must produce the exact
    // same payload as the unsigned one - this is what makes
    // verification able to reproduce what was actually signed.
    string canonical = check canonicalizeAgentCardBody(es256FixtureSignedCard());
    test:assertEquals(canonical, ES256_CANONICAL_PAYLOAD);
}

// ---- default-value stripping (spec 8.4.1), matching a2a-js's cleanEmpty
// exactly rather than a literal proto3 field-presence reading -----------

@test:Config {}
function testStripJcsDefaultsRemovesEmptyStringNullArrayObject() {
    json input = {a: "", b: (), c: [], d: {}, e: "kept", f: [1, 2]};
    json? result = stripJcsDefaults(input);
    map<json> stripped = <map<json>>result;
    test:assertFalse(stripped.hasKey("a"), "empty string must be stripped");
    test:assertFalse(stripped.hasKey("b"), "null must be stripped");
    test:assertFalse(stripped.hasKey("c"), "empty array must be stripped");
    test:assertFalse(stripped.hasKey("d"), "empty object must be stripped");
    test:assertEquals(stripped["e"], "kept");
    test:assertEquals(stripped["f"], <json>[1, 2]);
}

@test:Config {}
function testStripJcsDefaultsKeepsFalseAndZero() {
    // The one place this deliberately does NOT match literal proto3
    // zero-value semantics - matches what the real a2a-js cleanEmpty
    // actually does instead, which is what makes a real signature verify.
    json input = {flag: false, count: 0};
    json? result = stripJcsDefaults(input);
    map<json> stripped = <map<json>>result;
    test:assertEquals(stripped["flag"], false);
    test:assertEquals(stripped["count"], 0);
}

@test:Config {}
function testStripJcsDefaultsCollapsesToNilWhenEverythingIsEmpty() {
    json input = {a: "", b: [], c: {}};
    json? result = stripJcsDefaults(input);
    test:assertTrue(result is (), "an object whose every field strips to empty must itself signal empty to its parent");
}

@test:Config {}
function testStripJcsDefaultsRecursesIntoNestedArraysAndObjects() {
    json input = {wrapper: {inner: "", kept: "value", nested: [{x: ()}, {y: "z"}]}};
    json? result = stripJcsDefaults(input);
    map<json> stripped = <map<json>>result;
    map<json> wrapper = <map<json>>stripped["wrapper"];
    test:assertFalse(wrapper.hasKey("inner"));
    test:assertEquals(wrapper["kept"], "value");
    json[] nested = <json[]>wrapper["nested"];
    test:assertEquals(nested.length(), 1,
            "the {x: null} element strips to fully empty and must be dropped from the array entirely, not kept as {}");
}

// ---- verification against real, external (a2a-js-generated) signatures

@test:Config {}
function testVerifyAgentCardSignatureEs256AgainstRealA2aJsSignature() returns error? {
    // The key provider is a plain function reference, not a closure: an
    // isolated lambda can't safely capture a mutable outer-scope
    // variable like crypto:PublicKey, so each fixture key is resolved by
    // calling the (state-free) fixture function directly instead.
    check verifyAgentCardSignature(es256FixtureSignedCard(), verifyingKeyProviderForEcFixture);
}

isolated function verifyingKeyProviderForEcFixture(string kid, string? jku) returns crypto:PublicKey|error {
    test:assertEquals(kid, "fixture-ec-key-1");
    return ecFixturePublicKey();
}

@test:Config {}
function testVerifyAgentCardSignatureRs256AgainstRealA2aJsSignature() returns error? {
    check verifyAgentCardSignature(rs256FixtureSignedCard(), verifyingKeyProviderForRsaFixture);
}

isolated function verifyingKeyProviderForRsaFixture(string kid, string? jku) returns crypto:PublicKey|error {
    test:assertEquals(kid, "fixture-rsa-key-1");
    return rsaFixturePublicKey();
}

@test:Config {}
function testVerifyAgentCardSignatureFailsOnTamperedCard() returns error? {
    map<json> tampered = <map<json>>es256FixtureSignedCard().clone();
    tampered["name"] = "TAMPERED Agent Name";

    error? result = verifyAgentCardSignature(tampered, isolated function(string kid, string? jku) returns crypto:PublicKey|error {
        return ecFixturePublicKey();
    });
    test:assertTrue(result is AgentCardSignatureError,
            "a tampered field changes the canonical payload, so the same signature must no longer verify");
}

@test:Config {}
function testVerifyAgentCardSignatureFailsWithWrongKey() returns error? {
    // The RSA fixture's key, used to try to verify the EC-signed card -
    // structurally the wrong key type entirely, must fail cleanly rather
    // than panic or error opaquely.
    error? result = verifyAgentCardSignature(es256FixtureSignedCard(), isolated function(string kid, string? jku) returns crypto:PublicKey|error {
        return rsaFixturePublicKey();
    });
    test:assertTrue(result is AgentCardSignatureError);
}

@test:Config {}
function testVerifyAgentCardSignatureFailsWithNoSignatures() {
    json cardWithNoSignatures = es256FixtureCard();
    error? result = verifyAgentCardSignature(cardWithNoSignatures, isolated function(string kid, string? jku) returns crypto:PublicKey|error {
        return error("should never be called - there is nothing to look a key up for");
    });
    test:assertTrue(result is AgentCardSignatureError);
}

@test:Config {}
function testVerifyAgentCardSignatureFailsOnUnsupportedAlgorithm() returns error? {
    map<json> card = <map<json>>es256FixtureCard().clone();
    // A syntactically well-formed but unimplemented algorithm (HS256 -
    // symmetric, not something an AgentCard signature would legitimately
    // use, but exactly the kind of unexpected `alg` a malformed or
    // unusual card could carry).
    json unsupportedHeader = {alg: "HS256", kid: "irrelevant", typ: "JOSE"};
    string protectedB64 = encodeBase64Url(unsupportedHeader.toJsonString().toBytes());
    card["signatures"] = [{protected: protectedB64, signature: encodeBase64Url("not-a-real-signature".toBytes())}];

    error? result = verifyAgentCardSignature(card, isolated function(string kid, string? jku) returns crypto:PublicKey|error {
        return error("should never be called for an algorithm this library doesn't implement");
    });
    test:assertTrue(result is AgentCardSignatureError,
            "an unsupported alg must fail this entry (and, being the only entry, the whole verification), not crash");
}

@test:Config {}
function testVerifyAgentCardSignatureFailsOnMalformedProtectedHeader() {
    json card = es256FixtureCard();
    map<json> withBadSignature = <map<json>>card.clone();
    withBadSignature["signatures"] = [{protected: "not-valid-base64url!!!", signature: "alsonotvalid"}];

    error? result = verifyAgentCardSignature(withBadSignature, isolated function(string kid, string? jku) returns crypto:PublicKey|error {
        return error("should never be called - the protected header can't even be decoded");
    });
    test:assertTrue(result is AgentCardSignatureError);
}

// ---- base64url round-trips (encodeBase64Url/decodeBase64Url) ----------

@test:Config {}
function testBase64UrlRoundTripsArbitraryBytes() returns error? {
    byte[] original = [0, 1, 2, 253, 254, 255, 62, 63, 64];
    string encoded = encodeBase64Url(original);
    test:assertFalse(encoded.includes("+"), "base64url must never contain '+'");
    test:assertFalse(encoded.includes("/"), "base64url must never contain '/'");
    test:assertFalse(encoded.includes("="), "base64url, as used in JWS, is unpadded");
    byte[] decoded = check decodeBase64Url(encoded);
    test:assertEquals(decoded, original);
}

@test:Config {}
function testBase64UrlDecodesRealJwsProtectedHeader() returns error? {
    // The exact protected-header segment from the ES256 fixture above -
    // a real, externally-produced base64url string, not a round-trip of
    // our own encoder.
    byte[] decoded = check decodeBase64Url("eyJhbGciOiJFUzI1NiIsImtpZCI6ImZpeHR1cmUtZWMta2V5LTEiLCJ0eXAiOiJKT1NFIn0");
    string headerJson = check string:fromBytes(decoded);
    json parsed = check headerJson.fromJsonString();
    map<json> header = check parsed.ensureType();
    test:assertEquals(header["alg"], "ES256");
    test:assertEquals(header["kid"], "fixture-ec-key-1");
    test:assertEquals(header["typ"], "JOSE");
}
